# Adicionando Colunas, Modificando Colunas e Valores

### Vamos pegar o nosso dataframe novamente

In [2]:
import pandas as pd
#importando os arquivos
vendas_df = pd.read_csv(r'Contoso - Vendas - 2017.csv', sep=';')
produtos_df = pd.read_csv(r'Contoso - Cadastro Produtos.csv', sep=';')
lojas_df = pd.read_csv(r'Contoso - Lojas.csv', sep=';')
clientes_df = pd.read_csv(r'Contoso - Clientes.csv', sep=';')

#limpando apenas as colunas que queremos
clientes_df = clientes_df[['ID Cliente', 'E-mail']]
produtos_df = produtos_df[['ID Produto', 'Nome do Produto']]
lojas_df = lojas_df[['ID Loja', 'Nome da Loja']]

#mesclando e renomeando os dataframes
vendas_df = vendas_df.merge(produtos_df, on='ID Produto')
vendas_df = vendas_df.merge(lojas_df, on='ID Loja')
vendas_df = vendas_df.merge(clientes_df, on='ID Cliente').rename(columns={'E-mail': 'E-mail do Cliente'})
display(vendas_df)

,Numero da Venda,Data da Venda,Data do Envio,ID Canal,ID Loja,ID Produto,ID Promocao,ID Cliente,Quantidade Vendida,Quantidade Devolvida,Nome do Produto,Nome da Loja,E-mail do Cliente
0,1,01/01/2017,02/01/2017,1,86,981,2,6825,9,1,A. Datum Advanced Digital Camera M300 Pink,Loja Contoso Austin,rbrumfieldmy@ameblo.jp
1,880458,23/11/2017,23/11/2017,0,306,235,10,6825,8,0,Litware Home Theater System 7.1 Channel M710 B...,Loja Contoso Europe Online,rbrumfieldmy@ameblo.jp
2,191019,20/03/2017,21/03/2017,1,172,376,2,6825,9,0,Adventure Works Laptop12 M1201 Silver,Loja Contoso Hartford,rbrumfieldmy@ameblo.jp
3,18610,08/01/2017,10/01/2017,2,200,448,2,6825,48,0,WWI Desktop PC1.80 E1801 Black,Loja Contoso Catalog,rbrumfieldmy@ameblo.jp
4,287704,23/04/2017,26/04/2017,3,76,280,1,6825,10,0,Contoso Home Theater System 2.1 Channel M1210 ...,Loja Contoso Beaumont No.1,rbrumfieldmy@ameblo.jp
...,...,...,...,...,...,...,...,...,...,...,...,...,...
980637,878244,23/11/2017,23/11/2017,0,110,889,4,347,12,1,Contoso Bluetooth Notebook Mouse E70 Silver,Loja Contoso Orlando,edowner9m@imdb.com
980638,920243,09/12/2017,10/12/2017,1,261,1367,5,38781,13,0,Contoso Expandable 3-Handset Cordless Phone Sy...,Loja Contoso Damascus No.1,ruben31@adventure-works.com
980639,467482,21/06/2017,25/06/2017,4,115,269,1,553,10,0,Contoso Home Theater System 4.1 Channel M1400 ...,Loja Contoso New York No.1,akuhnertfc@themeforest.net
980640,853643,13/11/2017,20/11/2017,7,115,809,4,38860,6,0,Contoso Dual USB Power Adapter - power adapter...,Loja Contoso New York No.1,anne5@adventure-works.com
980641,903958,02/12/2017,02/12/2017,0,222,1435,10,815,8,0,The Phone Company Touch Screen Phones SAW/On-w...,Loja Contoso Roma,ekorneevmm@instagram.com

In [4]:
vendas_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 980642 entries, 0 to 980641
Data columns (total 13 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Numero da Venda       980642 non-null  int64
 1   Data da Venda         980642 non-null  object
 2   Data do Envio         980642 non-null  object
 3   ID Canal              980642 non-null  int64
 4   ID Loja               980642 non-null  int64
 5   ID Produto            980642 non-null  int64
 6   ID Promocao           980642 non-null  int64
 7   ID Cliente            980642 non-null  int64
 8   Quantidade Vendida    980642 non-null  int64
 9   Quantidade Devolvida  980642 non-null  int64
 10  Nome do Produto       980642 non-null  object
 11  Nome da Loja          980642 non-null  object
 12  E-mail do Cliente     980642 non-null  object
dtypes: int64(8), object(5)
memory usage: 104.7+ MB

### Agora, e se quisermos acrescentar uma coluna com o mÃªs, o dia e o ano de cada venda (e nÃ£o sÃ³ a data completa)

### E agora, caso a gente queira modificar 1 valor especÃ­fico, como fazemos? Vamos importar novamente a base de produtos

In [ ]:
novo_produtos_df = pd.read_csv(r'Contoso - Cadastro Produtos.csv', sep=';')
display(novo_produtos_df.head())
#repare no .head() para pegar apenas os primeiros valores, Ã© bem comum esse uso para ter uma visÃ£o do que sÃ£o os dados

### Antes de entrar no prÃ³ximo exemplo, precisamos falar de 2 mÃ©todos:
    1. loc - permite pegar uma linha de acordo com o Ã­ndice dela. Ele dÃ¡ erro caso nÃ£o encontre o Ã­ndice. Isso Ã© interessante principalmente quando o Ã­ndice Ã© uma informaÃ§Ã£o relevante ao invÃ©s sÃ³ do nÃºmero do Ã­ndice ou quando queremos pegar alguma linha especÃ­fica do dataframe (ao invÃ©s de ir do inÃ­cio do dataframe atÃ© a linha 5, por exemplo).
        TambÃ©m podemos usar como loc[Ã­ndice_linha, Ã­ndice_coluna] para acessar um valor especÃ­fico e modificÃ¡-lo.
    2. iloc - enxerga o dataframe como linhas e colunas e consegue pegar o valor com um nÃºmero de linha e um nÃºmero de coluna. Repara que ele nÃ£o analisa o valor do Ã­ndice da linha e da coluna, apenas a posiÃ§Ã£o importa.
        Uso: iloc[num_linha, num_coluna]
        
- Vendo na prÃ¡tica

In [ ]:
novo_produtos_df = novo_produtos_df.set_index('Nome do Produto')
display(novo_produtos_df.head())

In [ ]:
#vamos pegar o preÃ§o produto Contoso Optical Wheel OEM PS/2 Mouse E60 Black
#por loc

#por iloc

### A empresa decidiu aumentar o preÃ§o do produto ID 873 (Contoso Wireless Laser Mouse E50 Grey) para 23 reais. Como fazemos, para modificar isso na nossa base?

In [ ]:
#novo_produtos_df.loc['Contoso Wireless Laser Mouse E50 Grey', 'Preco Unitario'] = 23